# Use the official MySQL base image
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=mysql_databases_micunextfork
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

# Expose port 3306
EXPOSE 3306
